Honor keyboard-interactive
Throw an exception when remote server requires 'keyboard-interactive'

    [SCP] Connecting to 192.168.2.2
    ERROR: Server requires 'keyboard-interactive' authentication method to be used
    be.certipost.hudson.plugin.HonorKeyboardInteractiveException: Server requires 'keyboard-interactive' authentication method to be used
	    at be.certipost.hudson.plugin.SCPUserInfo.promptKeyboardInteractive(SCPUserInfo.java:52)
	    at com.jcraft.jsch.UserAuthKeyboardInteractive.start(UserAuthKeyboardInteractive.java:130)
	    at com.jcraft.jsch.Session.connect(Session.java:419)
	    at com.jcraft.jsch.Session.connect(Session.java:150)
	    at be.certipost.hudson.plugin.SCPSite.createSession(SCPSite.java:156)

Otherwise return null, this will end up with an unstable build and a
stacktrace:

    ERROR: Failed to upload files
    com.jcraft.jsch.JSchException: Auth cancel
	    at com.jcraft.jsch.Session.connect(Session.java:451)
	    at com.jcraft.jsch.Session.connect(Session.java:150)

Signed-off-by: Mykola Nikishov <mn@mn.com.ua>